import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PiMoonThin } from "react-icons/pi";
import { FilterGenre } from "./components/FilterGenre";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <div className="flex items-center gap-2 w-[375px] h-[59px] p-5 justify-between">
        <div className="flex gap-2">
          <svg width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M4.83268 1.16675V17.8334M13.166 1.16675V17.8334M0.666016 9.50008H17.3327M0.666016 5.33341H4.83268M0.666016 13.6667H4.83268M13.166 13.6667H17.3327M13.166 5.33341H17.3327M2.48268 1.16675H15.516C16.5193 1.16675 17.3327 1.9801 17.3327 2.98341V16.0167C17.3327 17.0201 16.5193 17.8334 15.516 17.8334H2.48268C1.47936 17.8334 0.666016 17.0201 0.666016 16.0167V2.98341C0.666016 1.9801 1.47936 1.16675 2.48268 1.16675Z" stroke="#4338CA" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
          <p className='text-[16px] font-bold italic text-[#4338CA]'>Movie Z</p>
        </div>   
        <div className="flex gap-3">
          <FilterGenre/>
          <button className="p-2 rounded-md border-[1px] border-[#E4E4E7]">
            <PiMoonThin className="w-[16px] h-[16px] text-black" />
          </button> 
        </div> 
      </div>
        {children}
        
      {/* <footer className="w-full h-[280px] bg-[#4338CA] flex justify-center items-center absolute bottom-0 left-0">
        <div className="w-[1280px] h-[200px] flex justify-between">
          <div className="w-[247px] h-[200px] text-white flex flex-col gap-3">
            <div className="flex gap-2">
             <img src='/film.png' className='w-[20px] h-[20px]'/>
             <p className='text-[16px] italic'>Movie Z</p>
            </div>
            <p className='text-[14px]'>© 2024 Movie Z. All Rights Reserved.</p>
          </div>
          <div className="w-[913px] h-[200px] flex justify-between">
            <div className='w-[274px] h-[52px]'></div>
            <div className='w-[174px] h-[200px] text-white flex flex-col gap-3 text-[14px]'>
              <p>Contact Information</p>
              <div className="flex gap-3 items-center">
                <img src='/email.png' className='w-[16px] h-[16px]'/>
                <p>Email: support@movieZ.com</p>
              </div>
              <div className="flex gap-3 items-center">
                <img src='/phone.png' className='w-[16px] h-[16px]'/>
                <p>Phone: <br/> +976 (11) 123-4567</p>
              </div>
            </div>
            <div className='w-[274px] h-[52px] text-white flex flex-col gap-3 text-[14px]'>
              <p>Follow us</p>
              <p>Facebook Instagram Twitter Youtube</p>
            </div>
          </div>
        </div>
      </footer> */}

      <footer className="w-full h-[308px] bg-[#4338CA] bottom-0 left-0 flex justify-center items-center">
        <div className='w-[335px] h-[228px] flex flex-col justify-between'>
          <div className="w-[247px] h-[52px] text-white flex flex-col gap-3 ">
            <div className="flex gap-2">
             <img src='/film.png' className='w-[20px] h-[20px]'/>
             <p className='text-[16px] font-bold italic'>Movie Z</p>
            </div>
            <p className='text-[14px]'>© 2024 Movie Z. All Rights Reserved.</p>
          </div>
          <div className='flex justify-between w-[335px] h-[148px]'>
            <div className='h-[136px] w-[174px] text-[14px] text-white flex flex-col justify-between'>
            <p>Contact Information</p>
              <div className="flex gap-3 items-center">
                <img src='/email.png' className='w-[16px] h-[16px]'/>
                <p>Email: support@movieZ.com</p>
              </div>
              <div className="flex gap-3 items-center">
                <img src='/phone.png' className='w-[16px] h-[16px]'/>
                <p>Phone: <br/> +976 (11) 123-4567</p>
              </div>
            </div>
            <div className='h-[148px] w-[113px] flex flex-col justify-between text-white text-[14px]'>
              <p>Follow us</p>
              <p className='font-semibold'>Facebook</p>
              <p className='font-semibold'>Instagram</p>
              <p className='font-semibold'>Twitter</p>
              <p className='font-semibold'>Youtube</p>
            </div>
          </div>
        </div>
      </footer>
      </body>
     
    </html>
  );
}
